# Linux checks
---
- name: Check if Oracle installed on the linux machine
  ansible.builtin.stat:
    path: /etc/oratab
    register: st

- name: Writing output
  ansible.builtin.debug:
    msg: "Oracle installed"
  when: st.stat.exists
