---
- name: Include Linux tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_facts.os_family != "Windows"

- name: Include Windows tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_facts.os_family == "Windows"
